# 1. Gunakan image dasar Node.js versi 22
FROM node:22.18.0

# 2. Tentukan direktori kerja di dalam container
WORKDIR /app

# 3. Salin file package.json dan package-lock.json untuk menginstal dependensi
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Salin semua file aplikasi Next.js ke dalam container
COPY . .

# 6. Build aplikasi Next.js
RUN npm run build

# 7. Tentukan port yang digunakan aplikasi
EXPOSE 3000

# 8. Jalankan aplikasi Next.js
CMD ["npm", "start"]
